export type User = {
    name: string,
    email: string,
    role: "USER"|"ADMIN"
}

export type UserSession = {
    user: User,
    token: string
}


export enum AuthStatus {
    INTERNAL_SERVER_ERROR = "SERVER_ERROR",
    SERVER_VALIDATION_ERROR = "SERVER_VALIDATION_ERROR",
    INVALID_NAME = "INVALID_NAME",
    INVALID_EMAIL = "INVALID_EMAIL",
    INVALID_PASSWORD = "INVALID_PASSWORD",
    INVALID_PASS_CONFIRMATION = "INVALID_PASS_CONFIRMATION",
    ALREADY_AUTHENTICATED = "ALREADY_AUTHENTICATED",
    EXPIRED_TOKEN = "INVALID_TOKEN",
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    NO_SESSION_COOKIE = "NO_SESSION_COOKIE",
    EMAIL_TAKEN = "EMAIL_TAKEN",
    AUTH_FAILURE = "AUTH_FAILURE",
    AUTH_SUCCESS = "AUTH_SUCCESS",
    MISSING_FIELD = "MISSING_FIELD",
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
}